FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . /app/

# Expose the port the app will run on
EXPOSE 8800

# Start uWSGI with the specified INI configuration file
CMD ["uwsgi", "--ini", "uwsgi.ini"]
