# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iv.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'iv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08iv.proto\x12\x0fincognito.vault\"\xa6\x01\n\x0e\x44ynamicRequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12?\n\x08metadata\x18\x02 \x03(\x0b\x32-.incognito.vault.DynamicRequest.MetadataEntry\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"A\n\x0f\x44ynamicResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xbf\x01\n\x15IncognitoVaultService\x12Q\n\x0c\x45xchangeData\x12\x1f.incognito.vault.DynamicRequest\x1a .incognito.vault.DynamicResponse\x12S\n\nStreamData\x12\x1f.incognito.vault.DynamicRequest\x1a .incognito.vault.DynamicResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNAMICREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_DYNAMICREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DYNAMICREQUEST']._serialized_start=30
  _globals['_DYNAMICREQUEST']._serialized_end=196
  _globals['_DYNAMICREQUEST_METADATAENTRY']._serialized_start=149
  _globals['_DYNAMICREQUEST_METADATAENTRY']._serialized_end=196
  _globals['_DYNAMICRESPONSE']._serialized_start=198
  _globals['_DYNAMICRESPONSE']._serialized_end=263
  _globals['_INCOGNITOVAULTSERVICE']._serialized_start=266
  _globals['_INCOGNITOVAULTSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
