# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import iv_pb2 as iv__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in iv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IncognitoVaultServiceStub(object):
    """Define a service with generic request/response types
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeData = channel.unary_unary(
                '/incognito.vault.IncognitoVaultService/ExchangeData',
                request_serializer=iv__pb2.DynamicRequest.SerializeToString,
                response_deserializer=iv__pb2.DynamicResponse.FromString,
                _registered_method=True)
        self.StreamData = channel.stream_stream(
                '/incognito.vault.IncognitoVaultService/StreamData',
                request_serializer=iv__pb2.DynamicRequest.SerializeToString,
                response_deserializer=iv__pb2.DynamicResponse.FromString,
                _registered_method=True)


class IncognitoVaultServiceServicer(object):
    """Define a service with generic request/response types
    """

    def ExchangeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IncognitoVaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeData,
                    request_deserializer=iv__pb2.DynamicRequest.FromString,
                    response_serializer=iv__pb2.DynamicResponse.SerializeToString,
            ),
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=iv__pb2.DynamicRequest.FromString,
                    response_serializer=iv__pb2.DynamicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'incognito.vault.IncognitoVaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('incognito.vault.IncognitoVaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IncognitoVaultService(object):
    """Define a service with generic request/response types
    """

    @staticmethod
    def ExchangeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incognito.vault.IncognitoVaultService/ExchangeData',
            iv__pb2.DynamicRequest.SerializeToString,
            iv__pb2.DynamicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/incognito.vault.IncognitoVaultService/StreamData',
            iv__pb2.DynamicRequest.SerializeToString,
            iv__pb2.DynamicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
